hr_app/urls.py
from django.urls import path

from . import views

app_name = 'hr_app'

urlpatterns = [
    path('', views.login, name='login'),
    path('requests', views.handle_request, name='request'),
    path('request/update/<int:request_id>/', views.update_request, name='updateRequest'),
    path('logout', views.logout, name='logout')
]

misfit_hr/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin', admin.site.urls),                         # Django admin for our use
    path('', include('hr_app.urls', namespace='hr'))        # Our app's namespace
]

hr_app/models.py
from django.db import models
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _


class User(models.Model):
    user_types = (
        ('1', 'EMPLOYEE'),
        ('2', 'HR'),
        ('3', 'MANAGER')
    )
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    type = models.CharField(max_length=100, choices=user_types, default= '1')
    is_logged_in = models.BooleanField(default=False)
    image = models.BinaryField(blank=True)

    def __str__(self):          # To show readable user list in admin
        user_types = {'1': 'EMPLOYEE', '2': 'HR', '3': 'MANAGER'}
        return self.name + ' - ' + self.email + ' (' + user_types[self.type] + ')'


class Request(models.Model):
    statuses = (
        ('1', 'Open'),
        ('2', 'HR Reviewed'),
        ('3', 'Processed')
    )
    details = models.CharField(max_length=255)
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_requester_id')   # Who creates requests
    processor = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='%(class)s_request_processor_id')     # Who processes requests
    status = models.CharField(max_length=20, choices=statuses, default='1')     # status is open when created


class UserForm(ModelForm):          # User login and register form
    class Meta:
        model = User
        fields = ['name', 'email']  # Only include these fields from model

    def clean_email(self):          # Validate user email
        email = self.cleaned_data['email']
        if email[email.index('@')+1:] != 'misfit.tech':
            raise ValidationError(_('Not a valid MISFIT email'))
        return email

hr_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models import Q

from .models import User, Request, UserForm


def login(request):                     # Login and Signup handler view.
    if 'user' in request.session:       # Authenticated user -> requests page
        return HttpResponseRedirect('/requests')
    data = {}
    if request.method == 'POST':        # performing a login or signup
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            if "signupButton" in request.POST:  # signup request
                user_form = UserForm()
                if User.objects.filter(Q(name=request.POST['name']) | Q(email=request.POST['email'])).count():
                    data['sign_up_failure'] = True  # Duplicate name / email
                else:
                    image_file = request.FILES['myImage'].file.read()
                    user = User(name=request.POST['name'], email=request.POST['email'], image=image_file)
                    user.save()
                    data['sign_up_success'] = True
            else:       # login request
                try:
                    user = User.objects.get(name=request.POST['name'], email=request.POST['email'])
                except User.DoesNotExist:       # invalid credential
                    user = None
                if user:
                    user.is_logged_in = True
                    user.save()
                    request.session['user'] = user.id
                    return HttpResponseRedirect('/requests')
                data['user_not_found'] = True
    else:
        user_form = UserForm()
    data['loginForm'] = user_form
    data['signupForm'] = UserForm()
    return render(request, 'login.html', data)


def handle_request(request):        # Request index page and request create
    if 'user' in request.session:
        data = {}
        user = User.objects.get(id=request.session['user'])
        if request.method == 'POST':    # Create request
            req = Request(details=request.POST['request_details'], requester_id=user.id, status='1')
            req.save()
            return JsonResponse({'request_saved': True})

        data['user'] = user
        if user.type == '1':    # Employee: Show user specific requests
            requests = Request.objects.filter(requester=user)
        elif user.type == '2':  # HR: Show all requests
            requests = Request.objects.all()
        else:                   # Manager: Show HR reviewed requests
            requests = Request.objects.filter(status='2')

        for idx, req in enumerate(requests):    # Add requester and processor info
            requests[idx].requested_user = User.objects.get(id=req.requester.id)
            if req.processor:       # Request processor exists
                requests[idx].processor_user = User.objects.get(id=req.processor.id)
        data['requests'] = requests
        return render(request, 'request.html', data)

    return HttpResponseRedirect('/')        # Not authorized


def logout(request):    # log out view
    user = User.objects.get(id=request.session['user'])
    user.is_logged_in = False
    user.save()
    del request.session['user']     # removing from session
    return HttpResponseRedirect('/')


def update_request(request, request_id):        # Update request details / status
    if 'user' in request.session:
        user = User.objects.get(id=request.session['user'])
        req = Request.objects.get(id=request_id)
        if request.method == 'POST':
            if 'requestDetails' in request.POST:    # Change details from Employee
                req.details = request.POST['requestDetails']
            if 'requestStatus' in request.POST:     # Change status from HR/Manager
                req.status = request.POST['requestStatus']
                if request.POST['requestStatus'] == '3':    # Save processor info
                    req.processor = user
            req.save()
            return HttpResponseRedirect('/requests')
        data = {'user': user, 'req': req}
        return render(request, 'request-update.html', data)
    return HttpResponseRedirect('/')        # Not authorized

hr_app/templates/index.html
<html>
<head>   {% load staticfiles %} {% load bootstrap3 %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
    <script src="{% static "jquery.min.js" %}"></script>
    <script src="{% static "bootstrap.min.js" %}"></script>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "jquery-ui.css" %}">
    <script src="{% static "jquery-ui.js" %}"></script>
    <script src="{% static "jquery-1.10.2.js" %}"></script>
    <style>
        th, td {
            vertical-align: middle !important;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header" style="width: 100%">
      		<a class="navbar-brand" href="{%url 'hr:login'%}"><font color='GreenYellow'>MISFIT HR</font></a>
            {% if user.is_logged_in %}
                <a class="navbar-brand pull-right" href="{%url 'hr:logout'%}"><font color='GreenYellow'>Logout</font></a>
                <span class="navbar-brand pull-right">{{ user.name }} ({{ user.email }}) </span>
            {% else %}
                <a class="navbar-brand pull-right" href="/admin"><font color='GreenYellow'>Admin</font></a>
            {% endif %}
        </div>
	</div>
</nav>
{% block body_content %} {% endblock %}

</body>
{% block jquery %} {% endblock %}
</html>

hr_app/templates/login.html
{% extends 'index.html' %}
{% load bootstrap3 %}
{% block body_content %}
    {% if sign_up_success %}
        <div class="alert alert-success">
            <strong>Sign up success!</strong> you can now log in.
        </div>
    {% endif %}
    {% if sign_up_failure %}
        <div class="alert alert-danger">
            <strong>Sign up Failed!</strong> Name / Email already exists.
        </div>
    {% endif %}
    <div class="row" style="margin-top: 100px">
        <div class="col-md-4 col-md-offset-2">
            <div class="panel panel-default" style="height: 342px">
            <h2 class="text-center">Log In</h2>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="{%url 'hr_app:login'%}" method="POST" style="margin-top: 20px;">
                        {% csrf_token %}
                        {% if user_not_found %}
                        <div class="alert alert-danger">
                          Invalid Name / Email
                        </div>
                        {% endif %}
                          {% for field in loginForm %}
                              <div class="form-group" >
                                {% bootstrap_field field %}
                                      <!--{% for error  in field.errors %}
                                       <!--   {{error}}
                                      {% endfor %} -->
                                </div>
                          {% endfor %}
                        <div class="form-group">
                        <button name="loginButton" id="loginButton" class="btn btn-primary btn-block">Log In</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
            <h2 class="text-center">Sign Up</h2>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form action="{%url 'hr_app:login' %}" enctype="multipart/form-data" method="POST" style="margin-top: 20px">
                        {% csrf_token %}
                            {% for field in signupForm %}
                              <div class="form-group" >
                                {% bootstrap_field field %}
                                      <!--{% for error  in field.errors %}
                                       <!--   {{error}}
                                      {% endfor %} -->
                                </div>
                             {% endfor %}
                            <div class="form-group" >
                                <label for="myImage">Upload your picture</label>
                                <input type="file" id="myImage" name="myImage" accept="image/x-png,image/gif,image/jpeg" />
                            </div>
                            <div class="form-group">
                                <button name="signupButton" id="signupButton" class="btn btn-primary btn-block">Sign Up</button>
                            </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock %}

hr_app/templates/request-update.html
{% extends 'index.html' %}
{% load bootstrap3 %}
{% block body_content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{% url 'hr:request' %}" class="btn btn-default btn-sm pull-left" style="margin: 5px">Back</a>
                <strong style="margin-right: 60px;font-size: 25px;" class="text-center"> Update Request #{{ req.id }} </strong>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form action="{%url 'hr:updateRequest' req.id %}" method="POST" style="margin-top: 50px; margin-bottom: 50px">
                    {% csrf_token %}
                    {% if user.type == '1' and req.status != '3' %}
                        <div class="form-group">
                            <label for="requestDetails">Details</label>
                            <textarea placeholder="Enter details up to 255 characters" name="requestDetails" class="form-control" rows="3">{{ req.details }}</textarea>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label for="details">Details</label>
                            <textarea name="details" class="form-control" disabled="disabled">{{ req.details }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="requestStatus">Status</label>
                            <select name="requestStatus"
                                    {% if req.status == '3' %} disabled="disabled" {% endif %}
                                    class="form-control" >
                                {% if user.type == '2' %}
                                    <option value="1"{% if req.status == '1' %} selected="selected" {% endif %}
                                    >Open</option>
                                {% endif %}
                                    <option value="2" {% if req.status == '2' %} selected="selected" {% endif %}
                                    >HR Reviewed</option>
                                    <option value="3" {% if req.status == '3' %} selected="selected" {% endif %}
                                    >Processed</option>
                            </select>
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <input type="submit" class="form-control btn btn-success">
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

hr_app/templates/request.html
{% extends 'index.html' %}
{% load bootstrap3 %}
{% block body_content %}
    {% if user.type == '1' %}
        <a href="#createRequestModal" data-toggle="modal" type="button" class="btn btn-success pull-right" style="margin-right: 110px; margin-bottom: 20px;">Create Request</a>
    {% else %}
        <a href="#" id="downloadPDF" type="button" class="btn btn-success pull-right" style="margin-right: 110px; margin-bottom: 20px;">Download PDF</a>
    {% endif %}
    <div class="row" id="requestContent">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">#</th>
                    {% if user.type == '2' or user.type == '3' %}
                  <th scope="col"> Requested By </th>
                    {% endif %}
                  <th scope="col"> Details</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                {% for request in requests %}
                    <tr>
                    <th scope="row"> {{ forloop.counter }} </th>
                        {% if user.type == '2' or user.type == '3' %}
                    <td>
                        {{ request.requested_user.name }} <br>
                        <a href="javascript:;" style="text-decoration: none; cursor:default">
                            {{ request.requested_user.email }}
                        </a>
                    </td>
                        {% endif %}
                    <td>{{ request.details }}</td>
                    <td>
                        {% if request.status == '1' %}
                        <span class="badge badge-primary">Open</span>
                        {% elif request.status == '2' %}
                        <span class="badge badge-info">HR reviewed</span>
                        {% else %}
                        <span class="badge badge-success">Processed</span> <br>
                            {% if request.processor_user %}
                            <small>by <strong>{{ request.processor_user.name }} </strong></small>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td class="editRequest">
                        {% if user.type == '1' and request.status == '1'%}
                        <a href="{% url 'hr:updateRequest' request.id %}" class="btn btn-sm">
                            Edit
                        </a>
                        {% endif %}
                        {% if user.type == '2' and request.status != '3' %}
                        <a href="{% url 'hr:updateRequest' request.id %}" class="btn btn-sm">
                            Edit
                        </a>
                        {% endif %}
                        {% if user.type == '3' and request.status == '2'%}
                        <a href="{% url 'hr:updateRequest' request.id %}" class="btn btn-sm">
                            Edit
                        </a>
                        {% endif %}
                    </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="createRequestModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3 class="modal-title">Create Request</h3>
                </div>
                <div class="modal-body">
                    <form>
                    <div class="form-group">
                        <label for="requestDetails"> Request Details</label>
                        <textarea class="form-control" name="requestDetails" id="requestDetails" rows="3" required></textarea>
                    </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default">Close</button>
                    <a type="button" id="request_submit_button" name="request_submit_button" class="btn btn-primary">Submit</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block jquery %}
    <script>
    $(document).ready(function() {
        $('#request_submit_button').addClass('disabled');
        $('#requestDetails').on('input propertychange', function() {
            if (this.value.length) {
                $('#request_submit_button').removeClass('disabled');
            } else {
                $('#request_submit_button').addClass('disabled');
            }
        });

        $('#downloadPDF').click(function() {
            var printContents = document.getElementById('requestContent').innerHTML;
            var popupWin = window.open('', '_blank', 'width=1200,height=750');
            popupWin.document.open();
            popupWin.document.write("<html><head><title>my div</title>");
            popupWin.document.write("<style>.editRequest{display: none;}</style>");

            popupWin.document.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">");
            popupWin.document.write(printContents);
            popupWin.print();
            popupWin.document.close();
        });

        $("#request_submit_button").click(function(event){
            console.log("submitted request", $('#requestDetails').val());
            $.ajax({
              type:"POST",
              url:"{%url 'hr:request' %}",
              data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                request_details: $('#requestDetails').val()
              },
              success : function(json) {
                if (json.request_saved)
                {
                    location.reload();
                }
                else{
                    console.log("failed");
                }
              },
            });
        });
    });
    </script>
{% endblock %}